language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: oA+fevpVQOdVEehatc8yHfrisSWpP/mfWQBoeABRQ6Jm+0dMe33g65w7Ja4fWGCbNhlGv3dzwdTTl3m5GuXVlhLFaYmJOIZNJaLNbjbmsDPEWeEHkxnd5keK98hPfrUq9O7xwdsSEU8ytMqq9zP63l94VOadoQL9ZE3A9JkMflfI1Q1Ad41y6dfKi832ZTUOz/gx4iz9ubOpYOn8x7VkdiXsGSYCXPLN/XA9ZUh+xdv6BrvjCRNkMbZI3qoEuFVG4hHMPrHj5t2mVmieZs83NIVCqKQdU0LhYI1+VXM4PWNM5Jsma5MuWVTIJqiI4eBEE/HDHnsWR/9S641QBi+CS95dTOEI+/pBtTnTEeADeP5mUKkwZXRFN21yuzpGayx8hFwE6paPr7jgSNrLeo1x4CKXB/qBWJ435gQCdDkdTgyrQewiR/qLJfLBNYi7istMHvRsPrYXv/4h6VZC6CAnDUhwrVedz6AFN72RFXz7cA8roX7ntYDJhLh/ZX0KcS+6C0rPsV1p0/rn3auxeufzFvsJVoB2ucumVf6dqMmoBf79bTYoaw84tbHoP9u3/pkxbnOxoGEHZ+OkvtAptraGX5b/KvBlz4U1HWVHoLtAKFlt08a1ysR5T6zKzvhqpLf8c3FFEFlW5pX6kHHgDthHF5ZVqAUS+D8Dsz2htLd7jqs=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: xQPiwQhmMqetRz7Omz+0R7kxSBzQ+SzKW2JE9bviFza1MDWtJ3Y8Gfey86UfH6RlVFrfvgVgU5pO1DwXyIBcSrd6Nek6a7y5G0vF1xexCNSthLRjHq7NYxWwb+kewM4VHS+8yNa43VAXPKlELM/nMQGP/ldEKw2uiCthYqLcyDpuYHpbI9MJ4qYDUInvB6NT461KNobFGKmgLchqTdoZ3WNANLYRT7yFLf2vumq7Yj92df1BL53xDydqjYEYc1U7DfVg3Encfd7/XIvddRB+ZHNPrauIv9i6K0m2QHSLowoYGxq8ugu/Dwyl+otLupo6xfEUhoUO/b2f7gc0BWfLoIA684Xs5NZLCaPeBYzPFKxf9GwGFwLGf5hVVXSilUem1fEJGei1z9+/vPb72BWQMBUHekASPWQ2ZhtaFYWPj5VUg/sLpNDa67s4Gp/Le3nlF5cgggEwmyLIepQdCchuOHYTNGTT3c2D4S2ifPoXRYQrzSVp0YBvoPP/76avLzllDgthSY1rkS6QKgkfrgSf6CVohv9JIBB9ngNQsyQokmGyWrqHZUx24HiULKYY0zpeYO0KVnvQ1tDMUpooNwG1XxTpYDvMcp/q48mNtZf/KfoEe/uLVIpXY3slRPkJ6IrWy84BINwXUctI5dVSsqa3l3JXZw3pD6Uf828a1VB0qHE=
sudo: false
