language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: bXrHdB1oztJbi5EXjxxrL2tXzu8lF11GhVlixtYmSgC10y+hGg+zsAZ4uyfbG3cabyrbu0zxWNBEcLedfqfJ/ADLJb0RewQsHj4s9u3Hn561zbaeE1R5tfxSOkl9Dxy8t8fz0fQVWRBkVE1PHsQ3R05878vWsuJ2n06Xagl4ZqDESiHJIfhTwsrmonrEJGbBfmgkthaPaoTI/WzTcHZEHdrBV0iIDVP1bQocKJyeYhA+4mgubWLAZ7zkkAmzsbbyqCGS3r05yOAamS/EupoGbcFcXKdswYg8abIsvuLU3smXUML2ZleXK+LsJijaZsqHXPNBsAgwGCraE/szkdQXwuIwJodr7U7Iu7hHYdUKWjCeHZVnU3rWC9GweNQOBlrukNcxJwoqrzq3xSBjWLR6BCKe7Fzf7WaDaqU4PKIWryTmZncj2w75dmb5P81MDz78Ih8khnPVaBRtzZbtO3RBsn7Zi28p6AlMQwRpvbN+K04PJ92HA1aevOFc01/0Fu2BNf9ZNN0F/x8Lwa7+l6SU57QQUBMUHkA5jd2U28o8zzPdbhHALUkUxzGm+Q9KKFogDvi0Z7myjgkHRII7dsp1AbbL/Pd9VLY+XzJbLkwD0UPiCkhuvFDXm0iNovq13V/J5tOcDOBKpwUe0G3vbHjkiaq47NsUea1XvZqXZQ1ssEo=
notifications:
  email: false
  slack:
    secure: xQPiwQhmMqetRz7Omz+0R7kxSBzQ+SzKW2JE9bviFza1MDWtJ3Y8Gfey86UfH6RlVFrfvgVgU5pO1DwXyIBcSrd6Nek6a7y5G0vF1xexCNSthLRjHq7NYxWwb+kewM4VHS+8yNa43VAXPKlELM/nMQGP/ldEKw2uiCthYqLcyDpuYHpbI9MJ4qYDUInvB6NT461KNobFGKmgLchqTdoZ3WNANLYRT7yFLf2vumq7Yj92df1BL53xDydqjYEYc1U7DfVg3Encfd7/XIvddRB+ZHNPrauIv9i6K0m2QHSLowoYGxq8ugu/Dwyl+otLupo6xfEUhoUO/b2f7gc0BWfLoIA684Xs5NZLCaPeBYzPFKxf9GwGFwLGf5hVVXSilUem1fEJGei1z9+/vPb72BWQMBUHekASPWQ2ZhtaFYWPj5VUg/sLpNDa67s4Gp/Le3nlF5cgggEwmyLIepQdCchuOHYTNGTT3c2D4S2ifPoXRYQrzSVp0YBvoPP/76avLzllDgthSY1rkS6QKgkfrgSf6CVohv9JIBB9ngNQsyQokmGyWrqHZUx24HiULKYY0zpeYO0KVnvQ1tDMUpooNwG1XxTpYDvMcp/q48mNtZf/KfoEe/uLVIpXY3slRPkJ6IrWy84BINwXUctI5dVSsqa3l3JXZw3pD6Uf828a1VB0qHE=
sudo: false
